# Hurtowe operacje na tablicach numpy: tzw. unfunc | universal functions |

def main(args):
    mojekaty = np.array( [0, 30, 45, 60, 0, 180, 270, 360] )
    sinusy = np.sin(mojekaty*np.pi/180)
    cosinusy = np.cos(mojekaty*np.pi/180)
    tangensy = np.tan(mojekaty*np.pi/180)
    print ("katy:")
    print (mojekaty)
    print("sinusy:")
    print (sinusy)
    print("cosinusy:")
    print(cosinusy)
    print ("tangensy:")
    print(tangensy)
    print ("-------------------------------------------------")
    t1 = np.array( [5, 10, 15, 20] )
    t2 = np.array( [2, 1, 2, 4] )
    t3 = np.array( [9, 16, 8, 81] )
    print ("t1 =", t1, end=" ")
    print()
    print ("t2 =", t2, end=" ")
    print()
    print ("t3 =", t3, end=" ")
    print()
    print()
    print("Negacja: ")
    print (np.negative(t1))
    print ()
    print("Dodawanie: ")
    print(np.add(t1, t2))
    print("Odejmowanie:")
    print(np.subtract(t1,t2))
    print("Mnożenie:")
    print(np.multiply(t1, t2))
    print("Dzielenie:")
    print(np.divide(t1, t2))
    print ("Pierwiastek kwadratowy: ")
    print (np.sqrt(t3))

if __name__=="__main__":
    import numpy as np
    import sys
    sys.exit(main(sys.argv))
